/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker'
// tslint:disable:object-literal-key-quotes

export const Meaning = t.iface([], {
	definition: 'string',
	synonyms: t.opt(t.array('string')),
	example: t.opt('string'),
	id: 'string',
})

export const EnrichedVerbForm = t.iface([], {
	wordUS: 'string',
	audioUS: t.opt('string'),
	wordUK: t.opt('string'),
	audioUK: t.opt('string'),
})

export const EnrichedVerb = t.iface([], {
	infinitive: EnrichedVerbForm,
	simplePast: EnrichedVerbForm,
	pastParticiple: EnrichedVerbForm,
	meanings: t.array(t.array(Meaning)),
	usageIndex: 'number',
	phonetic: 'string',
})

const exportedTypeSuite: t.ITypeSuite = {
	Meaning,
	EnrichedVerb,
	EnrichedVerbForm,
}
export default exportedTypeSuite
